on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        scala: [3.9.0-RC1-bin-20260429-88140bc-NIGHTLY, 3.9.0-RC1-bin-20260430-a24622b-NIGHTLY]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin
    - uses: sbt/setup-sbt@v1
    - run: sbt
           -v
           "++ ${{ matrix.scala }}!"
           compile
           clean
           compile
           clean
           compile
